name: CI

on: 
  push:
    branches:
      - "**"

    pull_request:
      branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # --- React Project ---
      # --- React Setup ---
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # --- Install dependences ---
      - name: Install React dependencies
        working-directory: ./FormFlow.React
        run: npm install

      # --- Run Tests ---

      - name: Install Node dependencies
        working-directory: ./FormFlow.React.Tests
        run: npm install

      - name: Run React tests
        working-directory: ./FormFlow.React.Tests
        run: npm test

      # --- Build application ---
      - name: Build React app
        working-directory: ./FormFlow.React
        run: npm run build

      # --- .NET Projects ---
      # --- .NET Setup ---
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      # --- Restore entire solution ---
      - name: Restore solution
        run: dotnet restore FormFlow.slnx

      # --- Build entire solution ---
      - name: Build solution
        run: dotnet build FormFlow.slnx --no-restore

      # --- Run ALL tests in the solution ---
      - name: Run Tests
        run: dotnet test FormFlow.slnx --no-build